# Generated by Django 5.1.2 on 2024-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=100)),
                ('tipo', models.CharField(choices=[('ME', 'Múltipla Escolha'), ('UE', 'Única Escolha')], default='UE', max_length=2)),
            ],
        ),
    ]
