# Generated by Django 5.1.2 on 2024-10-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_tipo_question_is_multiple_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='texto',
            new_name='question',
        ),
    ]
