# Generated by Django 5.1.2 on 2024-10-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('question', '0004_question_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='business.business'),
        ),
    ]
