# Generated by Django 5.1.2 on 2024-10-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('corporate_name', models.CharField(max_length=200)),
                ('doc_number', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('num_address', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('complement', models.CharField(blank=True, max_length=500, null=True)),
                ('group_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='group_business.groupbusiness')),
            ],
        ),
    ]
