# Generated by Django 5.1.2 on 2024-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('corporate_name', models.CharField(max_length=200)),
                ('doc_number', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=500)),
                ('num_address', models.IntegerField()),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('complement', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
