# Generated by Django 5.1.2 on 2024-10-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbusiness',
            name='password',
            field=models.CharField(default=123456, max_length=200),
            preserve_default=False,
        ),
    ]
