# Generated by Django 5.1.2 on 2024-10-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_business', '0002_groupbusiness_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbusiness',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
