# Generated by Django 5.1.2 on 2024-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_business', '0003_alter_groupbusiness_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbusiness',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
